import os

os.makedirs("backtests", exist_ok=True)

code = [
    "# backtests/spy_daily_backtest.py -- SPY Daily Strategy Backtest",
    "# Usage:",
    "#   python -m backtests.spy_daily_backtest --years 3",
    "#   python -m backtests.spy_daily_backtest --years 5 --source local",
    "#   python -m backtests.spy_daily_backtest --years 5 --csv results.csv --source local",
    "#   python -m backtests.spy_daily_backtest --years 5 --tune --source local",
    "",
    "from __future__ import annotations",
    "import os, sys, argparse",
    "from datetime import date, timedelta",
    "from typing import Optional",
    "import pandas as pd",
    "import numpy as np",
    "from loguru import logger",
    "",
    "sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))",
    "",
    "from signals.regime_detector import RegimeDetector, Regime",
    "from data.vix_client         import VIXClient",
    "from data.event_calendar     import EventCalendar",
    "import config",
    "",
    "",
    "HOLD_DAYS            = 5",
    "DEBIT_WIN_MOVE_PCT   = 1.0",
    "DEBIT_LOSE_MOVE_PCT  = 1.0",
    "CREDIT_WIN_FLAT_PCT  = 1.0",
    "CREDIT_LOSE_MOVE_PCT = 2.0",
    "CONDOR_WIN_RANGE_PCT = 2.0",
    "",
    "PNL = {",
    "    'debit_spread_win'  : +150,",
    "    'debit_spread_loss' : -200,",
    "    'debit_spread_be'   :  -30,",
    "    'credit_spread_win' : +120,",
    "    'credit_spread_loss': -180,",
    "    'credit_spread_be'  : +120,",
    "    'iron_condor_win'   : +130,",
    "    'iron_condor_loss'  : -220,",
    "    'skip'              :    0,",
    "}",
    "",
    "",
    "class BacktestDataLoader:",
    "    def __init__(self):",
    "        self.vix_client = VIXClient()",
    "",
    "    def load(self, years=3, source='polygon'):",
    "        logger.info(f'Loading {years} years of SPY + VIX (source={source})...')",
    "        if source == 'local':",
    "            spy_df = self._load_local(years)",
    "        else:",
    "            spy_df = self._load_polygon(years)",
    "        vix_df = self._load_vix(years)",
    "        if spy_df is None or len(spy_df) < 200:",
    "            raise RuntimeError(",
    "                'Not enough SPY data. '",
    "                'Run download_spy.py first, then use --source local'",
    "            )",
    "        logger.info(f'SPY: {len(spy_df)} days ({spy_df.index[0]} to {spy_df.index[-1]}) | VIX: {len(vix_df) if vix_df is not None else 0} days')",
    "        return spy_df, vix_df",
    "",
    "    def _load_local(self, years):",
    "        csv_path = os.path.join('backtests', 'spy_history.csv')",
    "        if not os.path.exists(csv_path):",
    "            raise FileNotFoundError(",
    "                'backtests/spy_history.csv not found. '",
    "                'Run: python download_spy.py'",
    "            )",
    "        df = pd.read_csv(csv_path, index_col=0, parse_dates=True)",
    "        df.columns = [c.lower() for c in df.columns]",
    "        df.index   = pd.to_datetime(df.index).date",
    "        df         = df.sort_index()",
    "        cutoff     = date.today() - timedelta(days=years * 365)",
    "        df         = df[df.index >= cutoff]",
    "        logger.info(f'Loaded {len(df)} bars from local CSV')",
    "        return df",
    "",
    "    def _load_polygon(self, years):",
    "        try:",
    "            from data.polygon_client import PolygonClient",
    "            client = PolygonClient()",
    "            df = client.get_bars('SPY', timeframe=config.SWING_PRIMARY_TIMEFRAME,",
    "                                  limit=years*260+100, days_back=years*365+60)",
    "            if df is not None:",
    "                df.index = pd.to_datetime(df.index).date",
    "            return df",
    "        except Exception as e:",
    "            logger.error(f'Polygon load failed: {e}')",
    "            return None",
    "",
    "    def _load_vix(self, years):",
    "        df = self.vix_client.get_history(days=years*365+60)",
    "        if df is not None:",
    "            df.index = pd.to_datetime(df.index).date",
    "        return df",
    "",
    "",
    "class SPYBacktest:",
    "    def __init__(self, spy_df, vix_df, event_cal, years=3):",
    "        self.spy_df    = spy_df",
    "        self.vix_df    = vix_df",
    "        self.event_cal = event_cal",
    "        self.years     = years",
    "        self.detector  = RegimeDetector()",
    "        self.results   = []",
    "",
    "    def run(self):",
    "        spy_dates = sorted(self.spy_df.index)",
    "        start_idx = 210",
    "        logger.info(f'Running backtest: {spy_dates[start_idx]} -> {spy_dates[-1]} ({len(spy_dates)-start_idx} days)')",
    "        for i in range(start_idx, len(spy_dates) - HOLD_DAYS):",
    "            today      = spy_dates[i]",
    "            hist_slice = self._get_spy_slice(i)",
    "            vix_today  = self._get_vix(today)",
    "            ivr_today  = self._get_ivr(today)",
    "            try:",
    "                r = self.detector.classify(spy_daily_df=hist_slice,",
    "                                           vix_current=vix_today,",
    "                                           ivr_current=ivr_today,",
    "                                           today=today)",
    "            except Exception as e:",
    "                logger.debug(f'Classify failed {today}: {e}')",
    "                continue",
    "            play         = self._regime_to_play(r)",
    "            outcome, pnl = self._simulate(today, spy_dates, i, play, r)",
    "            self.results.append({",
    "                'date'      : today,",
    "                'regime'    : r.regime.value,",
    "                'play'      : play,",
    "                'tradeable' : r.tradeable,",
    "                'vix'       : round(vix_today, 2),",
    "                'ivr'       : round(ivr_today, 1),",
    "                'adx'       : r.metrics.get('adx', 0),",
    "                'ma200_dist': r.metrics.get('ma200_dist_%', 0),",
    "                'outcome'   : outcome,",
    "                'pnl'       : pnl,",
    "                'confidence': r.confidence,",
    "            })",
    "        df = pd.DataFrame(self.results)",
    "        logger.info(f'Backtest complete: {len(df)} days')",
    "        return df",
    "",
    "    def _simulate(self, today, spy_dates, idx, play, r):",
    "        if play == 'skip' or not r.tradeable:",
    "            return 'skip', 0",
    "        entry = float(self.spy_df.loc[today, 'close'])",
    "        fi    = min(idx + HOLD_DAYS, len(spy_dates) - 1)",
    "        fwd   = float(self.spy_df.loc[spy_dates[fi], 'close'])",
    "        move  = (fwd - entry) / entry * 100",
    "        wdates = spy_dates[idx+1 : idx+HOLD_DAYS+1]",
    "        wclose = [float(self.spy_df.loc[d,'close']) for d in wdates if d in self.spy_df.index]",
    "        max_up   = max((p-entry)/entry*100 for p in wclose) if wclose else 0",
    "        max_down = min((p-entry)/entry*100 for p in wclose) if wclose else 0",
    "        if play == 'bull_debit':",
    "            if move >= DEBIT_WIN_MOVE_PCT:   return 'win',       PNL['debit_spread_win']",
    "            if move <= -DEBIT_LOSE_MOVE_PCT: return 'loss',      PNL['debit_spread_loss']",
    "            return 'breakeven', PNL['debit_spread_be']",
    "        if play == 'bear_debit':",
    "            if move <= -DEBIT_WIN_MOVE_PCT:  return 'win',       PNL['debit_spread_win']",
    "            if move >= DEBIT_LOSE_MOVE_PCT:  return 'loss',      PNL['debit_spread_loss']",
    "            return 'breakeven', PNL['debit_spread_be']",
    "        if play == 'bull_credit':",
    "            if move >= -CREDIT_WIN_FLAT_PCT:   return 'win',     PNL['credit_spread_win']",
    "            if move <= -CREDIT_LOSE_MOVE_PCT:  return 'loss',    PNL['credit_spread_loss']",
    "            return 'win', PNL['credit_spread_be']",
    "        if play == 'bear_credit':",
    "            if move <= CREDIT_WIN_FLAT_PCT:    return 'win',     PNL['credit_spread_win']",
    "            if move >= CREDIT_LOSE_MOVE_PCT:   return 'loss',    PNL['credit_spread_loss']",
    "            return 'win', PNL['credit_spread_be']",
    "        if play == 'iron_condor':",
    "            if abs(max_up) <= CONDOR_WIN_RANGE_PCT and abs(max_down) <= CONDOR_WIN_RANGE_PCT:",
    "                return 'win', PNL['iron_condor_win']",
    "            return 'loss', PNL['iron_condor_loss']",
    "        return 'skip', 0",
    "",
    "    @staticmethod",
    "    def _regime_to_play(r):",
    "        if not r.tradeable: return 'skip'",
    "        ivr  = r.metrics.get('ivr', 30)",
    "        dist = r.metrics.get('ma200_dist_%', 0)",
    "        if r.regime == Regime.TRENDING_UP_CALM:   return 'bull_credit' if ivr >= 50 else 'bull_debit'",
    "        if r.regime == Regime.TRENDING_DOWN_CALM: return 'bear_credit' if ivr >= 50 else 'bear_debit'",
    "        if r.regime == Regime.TRENDING_HIGH_VOL:  return 'bull_debit'  if dist >= 0  else 'bear_debit'",
    "        if r.regime == Regime.CHOPPY_LOW_VOL:     return 'iron_condor'",
    "        return 'skip'",
    "",
    "    def _get_spy_slice(self, idx):",
    "        spy_dates = sorted(self.spy_df.index)",
    "        sl = spy_dates[max(0, idx-250):idx]",
    "        df = self.spy_df.loc[sl].copy()",
    "        df.index = pd.to_datetime(df.index)",
    "        return df",
    "",
    "    def _get_vix(self, today):",
    "        if self.vix_df is not None and today in self.vix_df.index:",
    "            return float(self.vix_df.loc[today, 'close'])",
    "        if self.vix_df is not None:",
    "            past = [d for d in self.vix_df.index if d <= today]",
    "            if past: return float(self.vix_df.loc[past[-1], 'close'])",
    "        return 16.0",
    "",
    "    def _get_ivr(self, today):",
    "        if self.vix_df is None: return 30.0",
    "        cutoff = today - timedelta(days=365)",
    "        hist   = self.vix_df[(self.vix_df.index <= today) & (self.vix_df.index >= cutoff)]",
    "        if len(hist) < 20: return 30.0",
    "        cur    = self._get_vix(today)",
    "        lo, hi = float(hist['close'].min()), float(hist['close'].max())",
    "        spread = hi - lo",
    "        if spread < 0.5: return 50.0",
    "        return round(max(0.0, min(100.0, (cur - lo) / spread * 100)), 1)",
    "",
    "",
    "def _best_streak(df):",
    "    s = m = 0",
    "    for o in df['outcome']:",
    "        s = s+1 if o == 'win' else 0",
    "        m = max(m, s)",
    "    return m",
    "",
    "def _worst_streak(df):",
    "    s = m = 0",
    "    for o in df['outcome']:",
    "        s = s+1 if o == 'loss' else 0",
    "        m = max(m, s)",
    "    return m",
    "",
    "",
    "def print_report(df, years, source='polygon'):",
    "    if df.empty:",
    "        print('No results.'); return",
    "    traded  = df[df['tradeable'] == True]",
    "    skipped = df[df['tradeable'] == False]",
    "    total   = len(df)",
    "    trade_days = len(traded)",
    "    trade_rate = round(trade_days / total * 100, 1) if total else 0",
    "    wins   = len(traded[traded['outcome'] == 'win'])",
    "    losses = len(traded[traded['outcome'] == 'loss'])",
    "    bes    = len(traded[traded['outcome'] == 'breakeven'])",
    "    closed = wins + losses + bes",
    "    wr     = round(wins / closed * 100, 1) if closed else 0",
    "    tpnl   = int(traded['pnl'].sum())",
    "    avg    = round(traded['pnl'].mean(), 2) if len(traded) else 0",
    "    daily  = traded['pnl'].values",
    "    sharpe = (np.mean(daily) / (np.std(daily) + 1e-9)) * np.sqrt(252)",
    "    sep = '-' * 62",
    "    src_label = '(local CSV)' if source == 'local' else '(Polygon)'",
    "    print('')",
    "    print('=' * 62)",
    "    print(f'  SPY DAILY BACKTEST -- {years}-Year Replay {src_label}')",
    "    print(f'  {df[\"date\"].min()} -> {df[\"date\"].max()}')",
    "    print('=' * 62)",
    "    print(f'\\n  OVERVIEW\\n{sep}')",
    "    print(f'  Trading days analysed : {total:>6}')",
    "    print(f'  Days traded           : {trade_days:>6}  ({trade_rate}%)')",
    "    print(f'  Days skipped          : {len(skipped):>6}  ({100-trade_rate:.1f}%)')",
    "    print(f'  Wins                  : {wins:>6}')",
    "    print(f'  Losses                : {losses:>6}')",
    "    print(f'  Breakevens            : {bes:>6}')",
    "    print(f'  Win Rate              : {wr:>5.1f}%')",
    "    print(f'  Total P&L (1 contract): ${tpnl:>+,}')",
    "    print(f'  Avg P&L per trade day : ${avg:>+.2f}')",
    "    print(f'  Best win streak       : {_best_streak(traded):>6}')",
    "    print(f'  Worst loss streak     : {_worst_streak(traded):>6}')",
    "    print(f'  Sharpe (annualised)   : {sharpe:>6.2f}')",
    "    print(f'\\n  BY REGIME\\n{sep}')",
    "    print(f'  {\"Regime\":<28} {\"Days\":>5} {\"Win%\":>6} {\"P&L\":>9} {\"Skip%\":>7}')",
    "    for regime in sorted(df['regime'].unique()):",
    "        rdf  = df[df['regime'] == regime]",
    "        rt   = rdf[rdf['tradeable'] == True]",
    "        rw   = len(rt[rt['outcome'] == 'win'])",
    "        rc   = len(rt[rt['outcome'].isin(['win','loss','breakeven'])])",
    "        rwr  = round(rw/rc*100,1) if rc else 0",
    "        rpnl = int(rt['pnl'].sum())",
    "        rsk  = round(len(rdf[rdf['tradeable']==False])/len(rdf)*100,1)",
    "        print(f'  {regime.replace(\"_\",\" \").title()[:28]:<28} {len(rdf):>5} {rwr:>5.1f}% ${rpnl:>+8,} {rsk:>6.1f}%')",
    "    print(f'\\n  BY PLAY\\n{sep}')",
    "    print(f'  {\"Play\":<20} {\"Trades\":>7} {\"Win%\":>6} {\"P&L\":>9}')",
    "    pt = traded[traded['play'] != 'skip']",
    "    for play in sorted(pt['play'].unique()):",
    "        pdf = pt[pt['play'] == play]",
    "        pw  = len(pdf[pdf['outcome'] == 'win'])",
    "        pc  = len(pdf[pdf['outcome'].isin(['win','loss','breakeven'])])",
    "        pwr = round(pw/pc*100,1) if pc else 0",
    "        print(f'  {play:<20} {pc:>7} {pwr:>5.1f}% ${int(pdf[\"pnl\"].sum()):>+8,}')",
    "    print(f'\\n  CONDOR THRESHOLD SENSITIVITY\\n{sep}')",
    "    print(f'  {\"VIX <=\":>8} {\"Days\":>8} {\"Win%\":>8} {\"P&L\":>10}')",
    "    cdf = df[df['play'] == 'iron_condor']",
    "    for vt in [13, 14, 15, 16, 17, 18]:",
    "        sub  = cdf[cdf['vix'] <= vt]",
    "        sw   = len(sub[sub['outcome'] == 'win'])",
    "        sc   = len(sub[sub['outcome'].isin(['win','loss','breakeven'])])",
    "        swr  = round(sw/sc*100,1) if sc else 0",
    "        mark = ' <- current' if vt == 16 else ''",
    "        print(f'  {vt:>8} {sc:>8} {swr:>7.1f}% ${int(sub[\"pnl\"].sum()):>+9,}{mark}')",
    "    print(f'\\n  BY YEAR\\n{sep}')",
    "    print(f'  {\"Year\":<8} {\"Trades\":>7} {\"Win%\":>6} {\"P&L\":>9} {\"Sharpe\":>8}')",
    "    df2 = df.copy()",
    "    df2['year'] = [str(d.year) for d in df2['date']]",
    "    for yr in sorted(df2['year'].unique()):",
    "        ydf = df2[df2['year'] == yr]",
    "        yt  = ydf[ydf['tradeable'] == True]",
    "        yw  = len(yt[yt['outcome'] == 'win'])",
    "        yc  = len(yt[yt['outcome'].isin(['win','loss','breakeven'])])",
    "        ywr = round(yw/yc*100,1) if yc else 0",
    "        yp  = int(yt['pnl'].sum())",
    "        yd  = yt['pnl'].values",
    "        ysh = round((np.mean(yd)/(np.std(yd)+1e-9))*np.sqrt(252),2) if len(yd)>1 else 0",
    "        print(f'  {yr:<8} {yc:>7} {ywr:>5.1f}% ${yp:>+8,} {ysh:>8.2f}')",
    "    print('\\n' + '=' * 62 + '\\n')",
    "",
    "",
    "def run_threshold_tune(spy_df, vix_df):",
    "    import signals.regime_detector as rd",
    "    orig_adx, orig_vix = rd.ADX_TREND_MIN, rd.VIX_CALM_MAX",
    "    results = []",
    "    cal = EventCalendar()",
    "    print('\\n  THRESHOLD TUNER -- Grid search ADX + VIX')",
    "    print('-' * 72)",
    "    print(f'  {\"ADX\":>6} {\"VIX\":>6} {\"Trades\":>8} {\"Win%\":>7} {\"P&L\":>10} {\"Sharpe\":>8}')",
    "    for adx in [15, 18, 20, 22, 25]:",
    "        for vix in [13, 14, 15, 16, 17, 18]:",
    "            rd.ADX_TREND_MIN = adx",
    "            rd.VIX_CALM_MAX  = vix",
    "            df = SPYBacktest(spy_df, vix_df, cal, years=5).run()",
    "            t  = df[df['tradeable'] == True]",
    "            if len(t) < 20: continue",
    "            w  = len(t[t['outcome'] == 'win'])",
    "            c  = len(t[t['outcome'].isin(['win','loss','breakeven'])])",
    "            wr = round(w/c*100,1) if c else 0",
    "            p  = int(t['pnl'].sum())",
    "            d  = t['pnl'].values",
    "            sh = round((np.mean(d)/(np.std(d)+1e-9))*np.sqrt(252),2)",
    "            results.append((adx, vix, c, wr, p, sh))",
    "    rd.ADX_TREND_MIN = orig_adx",
    "    rd.VIX_CALM_MAX  = orig_vix",
    "    results.sort(key=lambda x: x[5], reverse=True)",
    "    for adx, vix, trades, wr, pnl, sh in results[:15]:",
    "        mark = ' <- current' if adx == 20 and vix == 16 else ''",
    "        print(f'  {adx:>6} {vix:>6} {trades:>8} {wr:>6.1f}% ${pnl:>+9,} {sh:>7.2f}{mark}')",
    "    print('')",
    "",
    "",
    "def main():",
    "    p = argparse.ArgumentParser()",
    "    p.add_argument('--years',  type=int, default=3)",
    "    p.add_argument('--csv',    type=str, default=None)",
    "    p.add_argument('--tune',   action='store_true')",
    "    p.add_argument('--source', type=str, default='polygon', choices=['polygon','local'],",
    "                   help='polygon = Polygon API | local = backtests/spy_history.csv')",
    "    args = p.parse_args()",
    "    loader = BacktestDataLoader()",
    "    spy_df, vix_df = loader.load(years=args.years, source=args.source)",
    "    cal = EventCalendar()",
    "    bt  = SPYBacktest(spy_df, vix_df, cal, years=args.years)",
    "    df  = bt.run()",
    "    print_report(df, years=args.years, source=args.source)",
    "    if args.csv:",
    "        df.to_csv(args.csv, index=False)",
    "        print(f'  Results saved to: {args.csv}')",
    "    if args.tune:",
    "        run_threshold_tune(spy_df, vix_df)",
    "",
    "",
    "if __name__ == '__main__':",
    "    main()",
]

path = os.path.join("backtests", "spy_daily_backtest.py")
with open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(code) + "\n")

import ast
with open(path, "rb") as f:
    raw = f.read()
nulls     = raw.count(b"\x00")
non_ascii = sum(1 for b in raw if b > 127)
ast.parse(raw.decode("utf-8"))
print(f"Written: {path}")
print(f"Size: {len(raw)} bytes | Nulls: {nulls} | Non-ASCII: {non_ascii}")
print("Syntax: OK")
print("")
print("Next steps:")
print("  1. python download_spy.py")
print("  2. python write_backtest.py")
print("  3. python -m backtests.spy_daily_backtest --years 5 --source local")
